name: notype
summary: game client
description: Simple typeracer game.
version: '0.1'
confinement: strict

apps:
  notype:
    command: notype
    plugs: [network, network-bind, x11, opengl, home, audio-playback]

parts:
  notype:
    plugin: cmake
    source: src
    build-packages:
    - make
    - g++
    - libsfml-dev
    - libboost-all-dev
    stage-packages:
    - libsfml-dev
    - libboost-all-dev